### ISSUE TITLE
BinTray is gone, and downloads are no longer available

### ISSUE THREAD

**Issue by tsal** [CBIIT/yeti#27]
Any chance you could migrate your artifact hosting to GitHub? BinTray went away as of this year, and any non-enterprise artifacts are gone.

**Comment by majensen** [comment]
Sorry @tsal - just saw this. Yes I will put up on JFrog. Thanks for the heads-up

**Comment by majensen** [comment]
@tsal if you're still interested, please try the new links in the README
thanks
